"use client"
import styles from './page.module.css';
import Image from 'next/image';
import { useState } from 'react';
import Link from 'next/link';

export default function AIMemeOfTheDay() {
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [showModal, setShowModal] = useState(false);

  const toggleFullscreen = () => setIsFullscreen(!isFullscreen);
  const toggleModal = (e: React.MouseEvent) => {
    e.stopPropagation();
    setShowModal(!showModal);
  };

  const formatDate = (date: Date) => {
    return date.toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });
  };

  return (
    <div className={styles.container} onClick={toggleFullscreen}>
      <div className={styles.date}>{formatDate(new Date())}</div>
      <div className={styles.imageWrapper}>
        <Image
          src="/your-meme-file.jpg"
          alt="AI Generated Meme"
          width={1200}
          height={1200}
          className={styles.memeImage}
          priority
        />
      </div>
      <button 
        className={styles.helpButton} 
        aria-label="Help"
        onClick={toggleModal}
      >
        ?
      </button>
      {isFullscreen && (
        <div className={styles.fullscreenOverlay} onClick={toggleFullscreen}>
          <Image
            src="/your-meme-file.jpg"
            alt="AI Generated Meme"
            width={1200}
            height={1200}
            className={styles.fullscreenImage}
            priority
          />
        </div>
      )}
      {showModal && (
        <div className={styles.modal} onClick={toggleModal}>
          <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
            <button className={styles.closeButton} onClick={toggleModal}>×</button>
            <h2>Get it?</h2>
            <p>This meme was generated by:</p>
            <div style={{ margin: '1rem 0' }}>
              <Image
                src="/gpt4-logo.png"
                alt="ChatGPT 4.0 Logo"
                width={100}
                height={100}
              />
            </div>
            <p>using this prompt:</p>
            <blockquote style={{ margin: '1rem 0', fontStyle: 'italic' }}>
              "your prompt here"
            </blockquote>
            <Link href="/contribute" style={{ color: 'blue', textDecoration: 'underline' }}>
              Contribute your own prompt
            </Link>
            <p>and join a community of people interested in the hilarious complexity of humanity.</p>
            <p style={{ marginTop: '1rem' }}>Made you laugh? Made you think?<br />Share your thoughts with the world!</p>
            <div className={styles.socialLinks}>
              <Image src="/x-logo.png" alt="X" width={24} height={24} className={styles.socialIcon} />
              <Image src="/instagram-logo.png" alt="Instagram" width={24} height={24} className={styles.socialIcon} />
              <Image src="/facebook-logo.png" alt="Facebook" width={24} height={24} className={styles.socialIcon} />
              <Image src="/whatsapp-logo.png" alt="WhatsApp" width={24} height={24} className={styles.socialIcon} />
              <Image src="/email-icon.png" alt="Email" width={24} height={24} className={styles.socialIcon} />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}