// src/utils/firebase/types.ts (Updated for top 10 only)
// Base high score interface that all games will extend
export interface HighScore {
  id?: string;        // Document ID (auto-generated by Firestore)
  name: string;       // 3-letter name
  score: number;      // Raw score value (format varies by game)
  formattedScore: string; // Formatted score for display (e.g., "01:23" for time)
  timestamp: number;  // When the score was achieved
  isAllTimeHigh: boolean; // Whether this is the all-time high score
  gameType: GameType; // Type of game
}

// Game-specific high score types
export interface SurvivorPuzzleHighScore extends HighScore {
  moves: number;
  timeTaken: number;
}

export interface FifteenPuzzleHighScore extends HighScore {
  difficulty?: string;
  moves: number;
  timeTaken: number;
}

export interface PicturePuzzleHighScore extends HighScore {
  category: string;  // e.g., 'animals', 'artworks'
  moves: number;
  timeTaken: number;
}

export interface WordGameHighScore extends HighScore {
  wordGameType: 'hardle' | 'randle';
  guesses: number;
}

// Weekly data type is kept for backward compatibility, but we don't use weekNumber anymore
export interface WeekData {
  id?: string;
  currentWeekNumber: number;
  lastUpdated: number;
}

// Game identifier types
export type GameType = 'survivorPuzzle' | 'fifteenPuzzle' | 'picturePuzzle' | 'wordGame';